// MPEG-1 Layer III scale factor + Huffman (big_values/count1) decode.
//
// Consumes the per-granule/channel side info from mp3_frame_parser and a
// bit-serial cursor into mp3_bit_reservoir's byte-addressable main-data
// ring, starting at frame_read_start. Streams out (a) this frame's scale
// factor values and (b) all 576 decoded (unscaled, signed) spectral
// coefficients per granule/channel, one value at a time.
//
// Two real gotchas, both root-caused against an instrumented build of
// FFmpeg's actual decoder rather than by inspection (see docs/MP3.md):
// canonical Huffman code construction must replicate FFmpeg's specific
// order-sensitive algorithm, not textbook canonical construction; and
// part2_3_length covers the scale factors *and* the Huffman data, so
// Huffman decode cannot start at a granule's first bit.
//
// Huffman tables are stored as binary tries (rtl/mp3_huffman_nodes.hex +
// mp3_huffman_roots.hex, generated by tools/mp3_huffman_rom_gen.py), not
// range-addressed ROM: canonical codes of the same length are not
// guaranteed to occupy a contiguous code range (an earlier version of the
// Python reference assumed they were and failed) -- a trie is correct for
// any prefix code regardless of gaps. The two count1 (quadruples) tables
// share the same trie-walk hardware and ROM, roots 15 and 16, with a
// quad's 4-bit (v,w,x,y) symbol packed into the leaf format's y nibble.
module mp3_huffman_decoder (
    input wire clk, reset,

    // From mp3_frame_parser.
    input wire frame_valid,
    input wire stereo,
    input wire sample_rate_44k1,
    input wire scfsi [0:1][0:3],
    input wire [11:0] part2_3_length [0:3],
    input wire [8:0] big_values [0:3],
    input wire [3:0] scalefac_compress [0:3],
    input wire window_switching_flag [0:3],
    input wire [1:0] block_type [0:3],
    input wire mixed_block_flag [0:3],
    input wire [4:0] table_select [0:3][0:2],
    input wire [3:0] region0_count [0:3],
    input wire [2:0] region1_count [0:3],
    input wire count1table_select [0:3],

    // From mp3_bit_reservoir.
    input wire [10:0] frame_read_start,
    output wire [10:0] read_addr,
    input wire [7:0] read_data,

    // Scale factor stream: up to 22 values per granule/channel.
    output reg sf_valid,
    output reg [1:0] sf_gci,
    output reg [5:0] sf_index,
    output reg [3:0] sf_data,

    // Decoded spectral coefficient stream: exactly 576 values per
    // granule/channel (implicit trailing zeros included, matching the
    // Python reference's always-576-long output).
    output reg value_valid,
    output reg [1:0] value_gci,
    output reg [9:0] value_index,
    output reg signed [15:0] value_data,

    output reg gc_done,          // pulses once per granule/channel, after realignment
    output reg [1:0] gc_done_index,
    output reg frame_done        // pulses once all granule/channels for this frame are done
);

localparam
    IDLE=0, GC_START=1,
    SF_SHORT_L1=2, SF_SHORT_L1B=3, SF_SHORT_L2=4, SF_SHORT_L2B=5, SF_SHORT_PAD=6,
    SF_LONG_GROUP=7, SF_LONG_READ=8, SF_LONG_READB=9, SF_LONG_COPY=10, SF_SAVE_GR0=11, SF_LONG_PAD=39,
    GET_WAIT=12, GET_BIT=13,
    REGION_CALC=14, BV_REGION_START=15, BV_PAIR_START=16,
    NODE_FETCH=17, NODE_WAIT=18, NODE_CHECK=19, NODE_GOTBIT=20,
    BV_ESC_X=21, BV_ESC_XB=22, BV_SIGN_X=23, BV_SIGN_XB=24,
    BV_ESC_Y=25, BV_ESC_YB=26, BV_SIGN_Y=27, BV_SIGN_YB=28,
    BV_EMIT=29, BV_NEXT=30,
    C1_SIGN=32, C1_EMIT=33, C1_ZERO=34, C1_NEXT=35,
    ZERO_FILL=36, REALIGN=37, GC_NEXT=38;

reg [5:0] state, return_state;
reg gr_reg, ch_reg;
wire [1:0] gci = {gr_reg, ch_reg};
wire nch1 = ~l_stereo; // 1 = mono (only channel 0 is real)

// Local snapshot of this frame's side info, captured the instant
// frame_valid pulses. mp3_frame_parser starts collecting the *next*
// frame's header immediately afterward -- its output arrays are not held
// stable for the (many-cycle) duration of this module's decode, so every
// field must be copied here rather than read live from the parser ports.
reg l_stereo, l_sample_rate_44k1;
reg l_scfsi [0:1][0:3];
reg [11:0] l_part2_3_length [0:3];
reg [8:0] l_big_values [0:3];
reg [3:0] l_scalefac_compress [0:3];
reg l_window_switching_flag [0:3];
reg [1:0] l_block_type [0:3];
reg l_mixed_block_flag [0:3];
reg [4:0] l_table_select [0:3][0:2];
reg [3:0] l_region0_count [0:3];
reg [2:0] l_region1_count [0:3];
reg l_count1table_select [0:3];

reg [13:0] bit_pos;             // absolute bit cursor into the reservoir (11-bit byte addr + 3-bit offset)
reg [13:0] granule_start_bitpos;
reg [15:0] bits_value;
reg [4:0] bits_left;
assign read_addr = bit_pos[13:3];

task get_bits;
    input [4:0] n;
    input [5:0] dest;
    begin
        bits_left <= n;
        bits_value <= 0;
        return_state <= dest;
        state <= GET_WAIT;
    end
endtask

// -- Scale factors: ff_slen_table (mpegaudiodec_common.c) -------------
function [3:0] slen1_of;
    input [3:0] sfc;
    begin case (sfc)
        0,1,2,3: slen1_of = 0; 4: slen1_of = 3; 5,6,7: slen1_of = 1;
        8,9,10: slen1_of = 2; 11,12,13: slen1_of = 3; 14,15: slen1_of = 4;
    endcase end
endfunction
function [3:0] slen2_of;
    input [3:0] sfc;
    begin case (sfc)
        0,4: slen2_of = 0; 1,5,8,11: slen2_of = 1; 2,6,9,12,14: slen2_of = 2;
        3,7,10,13,15: slen2_of = 3;
    endcase end
endfunction
function [3:0] long_group_size;
    input [1:0] k;
    begin long_group_size = (k == 0) ? 4'd6 : 4'd5; end
endfunction

wire [3:0] slen1 = slen1_of(l_scalefac_compress[gci]);
wire [3:0] slen2 = slen2_of(l_scalefac_compress[gci]);

reg [3:0] sf_mem [0:38];
reg [3:0] gr0_sf_mem [0:1][0:38];
reg [5:0] sf_idx, sf_n, sf_base;
reg [1:0] sf_group;
reg [3:0] sf_cur_slen;

// -- Region sizing (big_values pairs per region, clamped) ------------
reg [11:0] band_index_rom [0:45];
initial $readmemh("rtl/mp3_band_index_long.hex", band_index_rom);
wire [5:0] band_row = l_sample_rate_44k1 ? 6'd0 : 6'd23;
reg [8:0] region_size [0:2];
reg [8:0] region_remaining;
reg [1:0] region_idx;

// -- Huffman trie ROM (15 big_values tables + 2 quad tables) ---------
reg [24:0] node_rom [0:2802];
reg [11:0] root_rom [0:16];
initial $readmemh("rtl/mp3_huffman_nodes.hex", node_rom);
initial $readmemh("rtl/mp3_huffman_roots.hex", root_rom);

reg [11:0] node_addr, cur_left, cur_right;
reg bv_mode; // 1 = big_values (x,y pair), 0 = count1 (packed v,w,x,y symbol)

function [9:0] ts_lookup; // {valid, root_idx[4:0], linbits[3:0]}
    input [4:0] ts;
    reg valid; reg [4:0] idx; reg [3:0] lb;
    begin
        valid = 1; lb = 0;
        case (ts)
            5'd1: idx=0; 5'd2: idx=1; 5'd3: idx=2; 5'd5: idx=3; 5'd6: idx=4;
            5'd7: idx=5; 5'd8: idx=6; 5'd9: idx=7; 5'd10: idx=8; 5'd11: idx=9;
            5'd12: idx=10; 5'd13: idx=11; 5'd15: idx=12;
            5'd16: begin idx=13; lb=1; end 5'd17: begin idx=13; lb=2; end
            5'd18: begin idx=13; lb=3; end 5'd19: begin idx=13; lb=4; end
            5'd20: begin idx=13; lb=6; end 5'd21: begin idx=13; lb=8; end
            5'd22: begin idx=13; lb=10; end 5'd23: begin idx=13; lb=13; end
            5'd24: begin idx=14; lb=4; end 5'd25: begin idx=14; lb=5; end
            5'd26: begin idx=14; lb=6; end 5'd27: begin idx=14; lb=7; end
            5'd28: begin idx=14; lb=8; end 5'd29: begin idx=14; lb=9; end
            5'd30: begin idx=14; lb=11; end 5'd31: begin idx=14; lb=13; end
            default: begin valid=0; idx=0; end // ts 0, 4, 14: "table 0" -- always (0,0), no bits
        endcase
        ts_lookup = {valid, idx, lb};
    end
endfunction

reg cur_table_valid;
reg [4:0] cur_table_idx;
reg [3:0] cur_linbits;

reg [9:0] running_idx;
reg [13:0] mag_x, mag_y; // magnitude before sign; max 15 + (2^13-1) needs 14 bits
reg sign_x, sign_y;
reg [3:0] quad_sym;
reg [1:0] quad_pos; // which of v,w,x,y (0..3) is currently being processed, MSB first

integer i;
always @(posedge clk) begin
    sf_valid <= 0;
    value_valid <= 0;
    gc_done <= 0;
    frame_done <= 0;

    if (reset) begin
        state <= IDLE;
        gr_reg <= 0; ch_reg <= 0;
    end else begin
        case (state)

        IDLE: if (frame_valid) begin
            bit_pos <= {frame_read_start, 3'd0};
            gr_reg <= 0; ch_reg <= 0;
            l_stereo <= stereo;
            l_sample_rate_44k1 <= sample_rate_44k1;
            for (i = 0; i < 4; i = i + 1) begin
                l_part2_3_length[i] <= part2_3_length[i];
                l_big_values[i] <= big_values[i];
                l_scalefac_compress[i] <= scalefac_compress[i];
                l_window_switching_flag[i] <= window_switching_flag[i];
                l_block_type[i] <= block_type[i];
                l_mixed_block_flag[i] <= mixed_block_flag[i];
                l_table_select[i][0] <= table_select[i][0];
                l_table_select[i][1] <= table_select[i][1];
                l_table_select[i][2] <= table_select[i][2];
                l_region0_count[i] <= region0_count[i];
                l_region1_count[i] <= region1_count[i];
                l_count1table_select[i] <= count1table_select[i];
            end
            for (i = 0; i < 2; i = i + 1) begin
                l_scfsi[i][0] <= scfsi[i][0];
                l_scfsi[i][1] <= scfsi[i][1];
                l_scfsi[i][2] <= scfsi[i][2];
                l_scfsi[i][3] <= scfsi[i][3];
            end
            state <= GC_START;
        end

        GC_START: begin
            granule_start_bitpos <= bit_pos;
            running_idx <= 0;
            sf_idx <= 0;
            sf_base <= 0;
            // block_type is only actually transmitted (meaningful) when
            // window_switching_flag=1; mp3_frame_parser doesn't write it
            // otherwise, so it can hold a stale value left over from an
            // earlier switched granule. Gate on window_switching_flag too,
            // matching mp3_header_reference.py's parse_side_info, which
            // forces block_type=0 in the non-switched branch explicitly.
            if (l_window_switching_flag[gci] && l_block_type[gci] == 2'd2) begin
                sf_n <= l_mixed_block_flag[gci] ? 5'd17 : 5'd18;
                state <= SF_SHORT_L1;
            end else begin
                sf_group <= 0;
                state <= SF_LONG_GROUP;
            end
        end

        // ---- short/mixed-block scale factors: n*slen1 then 18*slen2 then 3 zero ----
        SF_SHORT_L1: begin
            if (sf_idx == sf_n) begin
                sf_idx <= 0; state <= SF_SHORT_L2;
            end else if (slen1 == 0) begin
                sf_mem[sf_idx] <= 0;
                sf_valid <= 1; sf_gci <= gci; sf_index <= sf_idx; sf_data <= 0;
                sf_idx <= sf_idx + 5'd1;
            end else get_bits(slen1, SF_SHORT_L1B);
        end
        SF_SHORT_L1B: begin
            sf_mem[sf_idx] <= bits_value[3:0];
            sf_valid <= 1; sf_gci <= gci; sf_index <= sf_idx; sf_data <= bits_value[3:0];
            sf_idx <= sf_idx + 5'd1;
            state <= SF_SHORT_L1;
        end
        SF_SHORT_L2: begin
            if (sf_idx == 18) begin
                sf_idx <= 0; state <= SF_SHORT_PAD;
            end else if (slen2 == 0) begin
                sf_mem[sf_n + sf_idx] <= 0;
                sf_valid <= 1; sf_gci <= gci; sf_index <= sf_n + sf_idx; sf_data <= 0;
                sf_idx <= sf_idx + 5'd1;
            end else get_bits(slen2, SF_SHORT_L2B);
        end
        SF_SHORT_L2B: begin
            sf_mem[sf_n + sf_idx] <= bits_value[3:0];
            sf_valid <= 1; sf_gci <= gci; sf_index <= sf_n + sf_idx; sf_data <= bits_value[3:0];
            sf_idx <= sf_idx + 5'd1;
            state <= SF_SHORT_L2;
        end
        SF_SHORT_PAD: begin
            if (sf_idx == 3) state <= SF_SAVE_GR0;
            else begin
                sf_mem[sf_n + 18 + sf_idx] <= 0;
                sf_valid <= 1; sf_gci <= gci; sf_index <= sf_n + 18 + sf_idx; sf_data <= 0;
                sf_idx <= sf_idx + 5'd1;
            end
        end

        // ---- long-block scale factors: 4 groups, scfsi-gated copy-or-read ----
        // sf_base accumulates each group's size (0, 6, 11, 16) so group 1's
        // entries land after group 0's in sf_mem instead of overwriting them.
        SF_LONG_GROUP: begin
            sf_n <= {1'b0, long_group_size(sf_group)};
            sf_cur_slen <= (sf_group < 2'd2) ? slen1 : slen2;
            sf_idx <= 0;
            if (gr_reg == 1'b0 || !l_scfsi[ch_reg][sf_group]) state <= SF_LONG_READ;
            else state <= SF_LONG_COPY;
        end
        SF_LONG_READ: begin
            if (sf_idx == sf_n) begin
                sf_idx <= 0;
                sf_base <= sf_base + sf_n;
                if (sf_group == 2'd3) state <= SF_LONG_PAD;
                else begin sf_group <= sf_group + 2'd1; state <= SF_LONG_GROUP; end
            end else if (sf_cur_slen == 0) begin
                sf_mem[sf_base + sf_idx] <= 0;
                sf_valid <= 1; sf_gci <= gci; sf_index <= sf_base + sf_idx; sf_data <= 0;
                sf_idx <= sf_idx + 5'd1;
            end else get_bits(sf_cur_slen, SF_LONG_READB);
        end
        SF_LONG_READB: begin
            sf_mem[sf_base + sf_idx] <= bits_value[3:0];
            sf_valid <= 1; sf_gci <= gci; sf_index <= sf_base + sf_idx; sf_data <= bits_value[3:0];
            sf_idx <= sf_idx + 5'd1;
            state <= SF_LONG_READ;
        end
        SF_LONG_COPY: begin
            if (sf_idx == sf_n) begin
                sf_idx <= 0;
                sf_base <= sf_base + sf_n;
                if (sf_group == 2'd3) state <= SF_LONG_PAD;
                else begin sf_group <= sf_group + 2'd1; state <= SF_LONG_GROUP; end
            end else begin
                sf_mem[sf_base + sf_idx] <= gr0_sf_mem[ch_reg][sf_base + sf_idx];
                sf_valid <= 1; sf_gci <= gci; sf_index <= sf_base + sf_idx;
                sf_data <= gr0_sf_mem[ch_reg][sf_base + sf_idx];
                sf_idx <= sf_idx + 5'd1;
            end
        end

        SF_LONG_PAD: begin
            sf_mem[sf_base] <= 0;
            sf_valid <= 1; sf_gci <= gci; sf_index <= sf_base; sf_data <= 0;
            state <= SF_SAVE_GR0;
        end

        SF_SAVE_GR0: begin
            if (gr_reg == 1'b0)
                for (i = 0; i < 39; i = i + 1) gr0_sf_mem[ch_reg][i] <= sf_mem[i];
            state <= REGION_CALC;
        end

        GET_WAIT: state <= GET_BIT;
        GET_BIT: begin
            bits_value <= {bits_value[14:0], read_data[7 - bit_pos[2:0]]};
            bit_pos <= bit_pos + 14'd1;
            bits_left <= bits_left - 5'd1;
            state <= (bits_left == 1) ? return_state : GET_WAIT;
        end

        // ---- region sizing: fixed [18,288,288] for switched blocks, else band-index-driven ----
        REGION_CALC: begin : region_calc_blk
            reg [8:0] b0, b1, k0, k1;
            reg [5:0] sum22;
            if (l_window_switching_flag[gci]) begin
                k0 = (9'd18 < l_big_values[gci]) ? 9'd18 : l_big_values[gci];
                region_size[0] = k0;
                region_size[1] = l_big_values[gci] - k0;
                region_size[2] = 0;
            end else begin
                b0 = band_index_rom[{1'b0, band_row} + {5'd0, l_region0_count[gci]} + 9'd1];
                sum22 = {2'd0, l_region0_count[gci]} + {3'd0, l_region1_count[gci]} + 6'd2;
                b1 = band_index_rom[{1'b0, band_row} + ((sum22 > 6'd22) ? 9'd22 : {3'd0, sum22})];
                k0 = (b0 < l_big_values[gci]) ? b0 : l_big_values[gci];
                k1 = (b1 < l_big_values[gci]) ? b1 : l_big_values[gci];
                region_size[0] = k0;
                region_size[1] = k1 - k0;
                region_size[2] = l_big_values[gci] - k1;
            end
            region_idx <= 0;
            state <= BV_REGION_START;
        end

        BV_REGION_START: begin
            if (region_idx == 2'd3) begin
                state <= C1_NEXT;
            end else if (region_size[region_idx] == 0) begin
                region_idx <= region_idx + 2'd1;
            end else begin
                region_remaining <= region_size[region_idx];
                {cur_table_valid, cur_table_idx, cur_linbits} <= ts_lookup(l_table_select[gci][region_idx]);
                bv_mode <= 1;
                state <= BV_PAIR_START;
            end
        end

        BV_PAIR_START: begin
            if (region_remaining == 0) begin
                region_idx <= region_idx + 2'd1;
                state <= BV_REGION_START;
            end else if (!cur_table_valid) begin
                mag_x <= 0; mag_y <= 0; sign_x <= 0; sign_y <= 0;
                state <= BV_EMIT;
            end else begin
                node_addr <= root_rom[cur_table_idx];
                state <= NODE_FETCH;
            end
        end

        NODE_FETCH: state <= NODE_WAIT;
        NODE_WAIT: state <= NODE_CHECK;
        NODE_CHECK: begin
            cur_left <= node_rom[node_addr][23:12];
            cur_right <= node_rom[node_addr][11:0];
            if (node_rom[node_addr][24]) begin
                if (bv_mode) begin
                    mag_x <= {10'd0, node_rom[node_addr][7:4]};
                    mag_y <= {10'd0, node_rom[node_addr][3:0]};
                    sign_x <= 0; sign_y <= 0;
                    state <= BV_ESC_X;
                end else begin
                    quad_sym <= node_rom[node_addr][3:0];
                    quad_pos <= 0;
                    state <= C1_SIGN;
                end
            end else get_bits(5'd1, NODE_GOTBIT);
        end
        NODE_GOTBIT: begin
            node_addr <= bits_value[0] ? cur_right : cur_left;
            state <= NODE_FETCH;
        end

        // ---- big_values escape + sign ----
        BV_ESC_X: begin
            if (mag_x == 14'd15 && cur_linbits != 0) get_bits(cur_linbits, BV_ESC_XB);
            else state <= (mag_x != 0) ? BV_SIGN_X : BV_ESC_Y;
        end
        BV_ESC_XB: begin
            mag_x <= mag_x + {1'd0, bits_value[12:0]};
            state <= BV_SIGN_X;
        end
        BV_SIGN_X: get_bits(5'd1, BV_SIGN_XB);
        BV_SIGN_XB: begin
            sign_x <= bits_value[0];
            state <= BV_ESC_Y;
        end
        BV_ESC_Y: begin
            if (mag_y == 14'd15 && cur_linbits != 0) get_bits(cur_linbits, BV_ESC_YB);
            else state <= (mag_y != 0) ? BV_SIGN_Y : BV_EMIT;
        end
        BV_ESC_YB: begin
            mag_y <= mag_y + {1'd0, bits_value[12:0]};
            state <= BV_SIGN_Y;
        end
        BV_SIGN_Y: get_bits(5'd1, BV_SIGN_YB);
        BV_SIGN_YB: begin
            sign_y <= bits_value[0];
            state <= BV_EMIT;
        end

        BV_EMIT: begin
            value_valid <= 1; value_gci <= gci; value_index <= running_idx;
            value_data <= sign_x ? -$signed({2'd0, mag_x}) : $signed({2'd0, mag_x});
            running_idx <= running_idx + 10'd1;
            state <= BV_NEXT;
        end
        BV_NEXT: begin
            value_valid <= 1; value_gci <= gci; value_index <= running_idx;
            value_data <= sign_y ? -$signed({2'd0, mag_y}) : $signed({2'd0, mag_y});
            running_idx <= running_idx + 10'd1;
            region_remaining <= region_remaining - 9'd1;
            state <= BV_PAIR_START;
        end

        // ---- count1 (quadruples) ----
        C1_NEXT: begin
            if ((bit_pos - granule_start_bitpos >= {2'd0, l_part2_3_length[gci]}) || running_idx > 10'd572)
                state <= ZERO_FILL;
            else begin
                cur_table_idx <= l_count1table_select[gci] ? 5'd16 : 5'd15;
                bv_mode <= 0;
                node_addr <= root_rom[l_count1table_select[gci] ? 5'd16 : 5'd15];
                state <= NODE_FETCH;
            end
        end
        // quad_sym bit3..0 = v,w,x,y; process MSB-first (v) to LSB-first (y),
        // reading a sign bit only for a nonzero component -- matches
        // READ_FLIP_SIGN in mpegaudiodec_template.c's count1 loop exactly.
        C1_SIGN: begin
            if (quad_sym[3 - quad_pos]) get_bits(5'd1, C1_EMIT);
            else state <= C1_ZERO;
        end
        C1_ZERO: begin
            value_valid <= 1; value_gci <= gci; value_index <= running_idx;
            value_data <= 16'sd0;
            running_idx <= running_idx + 10'd1;
            if (quad_pos == 2'd3) state <= C1_NEXT;
            else begin quad_pos <= quad_pos + 2'd1; state <= C1_SIGN; end
        end
        C1_EMIT: begin
            value_valid <= 1; value_gci <= gci; value_index <= running_idx;
            value_data <= bits_value[0] ? -16'sd1 : 16'sd1;
            running_idx <= running_idx + 10'd1;
            if (quad_pos == 2'd3) state <= C1_NEXT;
            else begin quad_pos <= quad_pos + 2'd1; state <= C1_SIGN; end
        end

        ZERO_FILL: begin
            if (running_idx == 10'd576) state <= REALIGN;
            else begin
                value_valid <= 1; value_gci <= gci; value_index <= running_idx;
                value_data <= 16'sd0;
                running_idx <= running_idx + 10'd1;
            end
        end

        REALIGN: begin
            bit_pos <= granule_start_bitpos + {2'd0, l_part2_3_length[gci]};
            gc_done <= 1; gc_done_index <= gci;
            state <= GC_NEXT;
        end

        GC_NEXT: begin
            if ((nch1 && ch_reg == 1'b0) || (!nch1 && ch_reg == 1'b1)) begin
                ch_reg <= 0;
                if (gr_reg == 1'b1) begin frame_done <= 1; state <= IDLE; end
                else begin gr_reg <= 1'b1; state <= GC_START; end
            end else begin
                ch_reg <= ch_reg + 1'b1;
                state <= GC_START;
            end
        end

        default: state <= IDLE;
        endcase
    end
end

endmodule
