// Correctness-first scalar Vorbis Huffman decoder. It accepts one packed
// LSB-first bit at a time and scans the selected codebook's active leaves.
// A later fast-prefix cache can sit in front of this engine without changing
// its interface or the canonical tables generated by the setup parser.
module vorbis_huffman_decoder(
 input wire clk,input wire reset,
 input wire start,input wire [31:0] start_prefix,input wire [5:0] start_length,
 input wire [13:0] table_start,input wire [13:0] table_end,
 input wire bit_valid,input wire bit_data,output wire bit_ready,
 output reg [13:0] table_address=0,input wire [31:0] table_entry,input wire [31:0] table_codeword,
 output reg symbol_valid=0,input wire symbol_ready,output reg [17:0] symbol=0,
 output reg [5:0] symbol_length=0,output reg error=0
);
 localparam IDLE=0,GET_BIT=1,SCAN_WAIT=2,SCAN=3,OUTPUT=4;
 reg [2:0] state=IDLE;
 reg [31:0] prefix=0;
 reg [5:0] length=0;
 assign bit_ready=state==GET_BIT;
 always @(posedge clk)begin
  if(reset)begin state<=IDLE;prefix<=0;length<=0;table_address<=0;symbol_valid<=0;error<=0;end
  else case(state)
   IDLE:if(start)begin
    // A failed fast-prefix lookup has already proven that the first eight
    // bits do not form a leaf.  Seed the scalar decoder with those bits so it
    // does not rescan the entire codebook once for every short prefix length.
    prefix<=start_prefix;length<=start_length;table_address<=table_start;
    if(table_start>=table_end)begin error<=1;state<=IDLE;end else state<=GET_BIT;
   end
   GET_BIT:if(bit_valid)begin
    prefix<=prefix|({31'd0,bit_data}<<length);length<=length+1'b1;table_address<=table_start;state<=SCAN_WAIT;
   end
   SCAN_WAIT:state<=SCAN;
   SCAN:begin
    if(table_entry[5:0]==length&&table_codeword==prefix)begin
     symbol<=table_entry[23:6];symbol_length<=length;symbol_valid<=1;state<=OUTPUT;
    end else if(table_address+1'b1>=table_end)begin
     if(length==32)begin error<=1;state<=IDLE;end else state<=GET_BIT;
    end else begin table_address<=table_address+1'b1;state<=SCAN_WAIT;end
   end
   OUTPUT:if(symbol_valid&&symbol_ready)begin symbol_valid<=0;state<=IDLE;end
  endcase
 end
endmodule
